from enum import IntEnum

class ZibalResultCode(IntEnum):
    SUCCESS = 100
    MERCHANT_NOT_FOUND = 102
    MERCHANT_DISABLED = 103
    INVALID_MERCHANT = 104
    AMOUNT_TOO_LOW = 105
    INVALID_CALLBACK_URL = 106
    AMOUNT_TOO_HIGH = 113
    INVALID_NATIONAL_CODE = 114
